### ISSUE TITLE
Problem when you load up Discord while being connected to a voice channel

### ISSUE THREAD

**Issue by MaximeDawn** [Egrodo/DiscordPlugins#3]
When you CTRL+R while in a voice channel, or if Discord loads and you're in a voice channel, the button goes at the wrong place : 
![image](https://user-images.githubusercontent.com/20993007/79617765-8f2c7b80-8108-11ea-8e2f-d3dd280ed792.png)

After that, if you leave the voice channel, the button disapears and become unusable.
![image](https://user-images.githubusercontent.com/20993007/79617808-a79c9600-8108-11ea-9876-ce6c348a5881.png)

**Comment by Egrodo** [comment]
Thanks for the report! This should be fixed in 1.2.3, let me know if it's still happening.
