### ISSUE TITLE
Sometimes game activity toggle goes missing.

### ISSUE THREAD

**Issue by pcislocked** [Egrodo/DiscordPlugins#9]
when i start discord, toggle is not visible at all, just like when you dont have it installed. then i go to plugin settings and toggle off and back on the gameactivitytoggle plugin, then it works again. at least until next refresh or restart.

i have around 14 plugins installed. no themes installed.
![image](https://user-images.githubusercontent.com/50513999/98244233-23b0db00-1f80-11eb-80e5-d5e08dd97441.png)

some version info:
plugin v1.2.6 
stable 70781 
BBD 0.3.5 
host 0.0.308 
injector 0.6.2 
win10-64 10.0.19042

im not sure what is the problem.

**Comment by KlartNET** [comment]
because the plugin loaded on an unexpected page (such as the login page).
Try this PR: https://github.com/Egrodo/DiscordPlugins/pull/13/files
